def on_logo_pressed():
    pass
input.on_logo_event(TouchButtonEvent.PRESSED, on_logo_pressed)

def on_button_pressed_a():
    SuperBit.servo2(SuperBit.enServo.S1, 135)
input.on_button_pressed(Button.A, on_button_pressed_a)

def on_button_pressed_b():
    SuperBit.servo2(SuperBit.enServo.S1, 105)
input.on_button_pressed(Button.B, on_button_pressed_b)

SuperBit.motor_stop_all()
basic.show_string("OI, BIANCA!")
music.start_melody(music.built_in_melody(Melodies.DADADADUM),
    MelodyOptions.ONCE)
SuperBit.servo2(SuperBit.enServo.S1, 105)

def on_forever():
    SuperBit.servo2(SuperBit.enServo.S1, 105)
    basic.pause(500)
    SuperBit.servo2(SuperBit.enServo.S1, 135)
    basic.pause(500)
basic.forever(on_forever)

def on_forever2():
    SuperBit.RGB_Program().set_pixel_color(0, neopixel.colors(NeoPixelColors.RED))
    SuperBit.RGB_Program().set_pixel_color(1, neopixel.colors(NeoPixelColors.ORANGE))
    SuperBit.RGB_Program().set_pixel_color(2, neopixel.colors(NeoPixelColors.YELLOW))
    SuperBit.RGB_Program().set_pixel_color(3, neopixel.colors(NeoPixelColors.GREEN))
    SuperBit.RGB_Program().show()
    basic.show_icon(IconNames.HEART)
    basic.pause(1000)
    SuperBit.RGB_Program().set_pixel_color(0, neopixel.colors(NeoPixelColors.ORANGE))
    SuperBit.RGB_Program().set_pixel_color(1, neopixel.colors(NeoPixelColors.RED))
    SuperBit.RGB_Program().set_pixel_color(2, neopixel.colors(NeoPixelColors.YELLOW))
    SuperBit.RGB_Program().set_pixel_color(3, neopixel.colors(NeoPixelColors.GREEN))
    SuperBit.RGB_Program().show()
    basic.show_icon(IconNames.SMALL_HEART)
    basic.pause(1000)
    SuperBit.RGB_Program().set_pixel_color(0, neopixel.colors(NeoPixelColors.YELLOW))
    SuperBit.RGB_Program().set_pixel_color(1, neopixel.colors(NeoPixelColors.RED))
    SuperBit.RGB_Program().set_pixel_color(2, neopixel.colors(NeoPixelColors.ORANGE))
    SuperBit.RGB_Program().set_pixel_color(3, neopixel.colors(NeoPixelColors.GREEN))
    SuperBit.RGB_Program().show()
    basic.show_icon(IconNames.HEART)
    basic.pause(1000)
    SuperBit.RGB_Program().set_pixel_color(0, neopixel.colors(NeoPixelColors.GREEN))
    SuperBit.RGB_Program().set_pixel_color(1, neopixel.colors(NeoPixelColors.RED))
    SuperBit.RGB_Program().set_pixel_color(2, neopixel.colors(NeoPixelColors.ORANGE))
    SuperBit.RGB_Program().set_pixel_color(3, neopixel.colors(NeoPixelColors.YELLOW))
    SuperBit.RGB_Program().show()
    basic.show_icon(IconNames.SMALL_HEART)
    basic.pause(1000)
    SuperBit.RGB_Program().set_pixel_color(0, neopixel.colors(NeoPixelColors.BLUE))
    SuperBit.RGB_Program().set_pixel_color(1, neopixel.colors(NeoPixelColors.INDIGO))
    SuperBit.RGB_Program().set_pixel_color(2, neopixel.colors(NeoPixelColors.VIOLET))
    SuperBit.RGB_Program().set_pixel_color(3, neopixel.colors(NeoPixelColors.PURPLE))
    SuperBit.RGB_Program().show()
    basic.show_icon(IconNames.HEART)
    basic.pause(1000)
    SuperBit.RGB_Program().set_pixel_color(0, neopixel.colors(NeoPixelColors.INDIGO))
    SuperBit.RGB_Program().set_pixel_color(1, neopixel.colors(NeoPixelColors.BLUE))
    SuperBit.RGB_Program().set_pixel_color(2, neopixel.colors(NeoPixelColors.VIOLET))
    SuperBit.RGB_Program().set_pixel_color(3, neopixel.colors(NeoPixelColors.PURPLE))
    SuperBit.RGB_Program().show()
    basic.show_icon(IconNames.SMALL_HEART)
    basic.pause(1000)
    SuperBit.RGB_Program().set_pixel_color(0, neopixel.colors(NeoPixelColors.VIOLET))
    SuperBit.RGB_Program().set_pixel_color(1, neopixel.colors(NeoPixelColors.GREEN))
    SuperBit.RGB_Program().set_pixel_color(2, neopixel.colors(NeoPixelColors.BLUE))
    SuperBit.RGB_Program().set_pixel_color(3, neopixel.colors(NeoPixelColors.INDIGO))
    SuperBit.RGB_Program().show()
    basic.show_icon(IconNames.HEART)
    basic.pause(1000)
    SuperBit.RGB_Program().set_pixel_color(0, neopixel.colors(NeoPixelColors.PURPLE))
    SuperBit.RGB_Program().set_pixel_color(1, neopixel.colors(NeoPixelColors.WHITE))
    SuperBit.RGB_Program().set_pixel_color(2, neopixel.colors(NeoPixelColors.BLUE))
    SuperBit.RGB_Program().set_pixel_color(3, neopixel.colors(NeoPixelColors.GREEN))
    SuperBit.RGB_Program().show()
    basic.show_icon(IconNames.SMALL_HEART)
    basic.pause(1000)
    SuperBit.RGB_Program().set_pixel_color(0, neopixel.colors(NeoPixelColors.WHITE))
    SuperBit.RGB_Program().set_pixel_color(1, neopixel.colors(NeoPixelColors.PURPLE))
    SuperBit.RGB_Program().set_pixel_color(2, neopixel.colors(NeoPixelColors.INDIGO))
    SuperBit.RGB_Program().set_pixel_color(3, neopixel.colors(NeoPixelColors.VIOLET))
    SuperBit.RGB_Program().show()
    basic.pause(1000)
basic.forever(on_forever2)

def on_forever3():
    SuperBit.motor_run(SuperBit.enMotors.M1, 255)
    SuperBit.motor_run(SuperBit.enMotors.M3, 255)
    basic.pause(500)
    SuperBit.motor_run(SuperBit.enMotors.M1, -255)
    SuperBit.motor_run(SuperBit.enMotors.M3, -255)
    basic.pause(500)
    SuperBit.motor_run(SuperBit.enMotors.M1, -255)
    SuperBit.motor_run(SuperBit.enMotors.M3, 255)
    basic.pause(500)
    SuperBit.motor_run(SuperBit.enMotors.M1, 255)
    SuperBit.motor_run(SuperBit.enMotors.M3, -255)
    basic.pause(500)
    SuperBit.motor_run(SuperBit.enMotors.M1, -255)
    SuperBit.motor_run(SuperBit.enMotors.M3, 255)
    basic.pause(500)
    SuperBit.motor_run(SuperBit.enMotors.M1, 255)
    SuperBit.motor_run(SuperBit.enMotors.M3, -255)
    basic.pause(500)
    SuperBit.motor_run(SuperBit.enMotors.M1, 255)
    SuperBit.motor_run(SuperBit.enMotors.M3, 0)
    basic.pause(500)
    SuperBit.motor_run(SuperBit.enMotors.M1, 0)
    SuperBit.motor_run(SuperBit.enMotors.M3, 255)
    basic.pause(500)
basic.forever(on_forever3)
